/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'en': {
    'label_general_settings': 'General Settings',
    'label_web_server': 'Web Server',
    'label_port': 'Port',
    'label_port_help': 'Port for the web server (PWA application)',
    'label_api_configuration': 'API Configuration',
    'label_api_keys': 'API Keys',
    'label_api_keys_help': 'Kinopoisk API keys (one or more). The adapter will use them in rotation. Press \'+\' to add a new key.',
    'label_api_key': 'API Key',
    'label_get_api_key': 'Get your API key at: https://api.kinopoisk.dev/',
    'label_synchronization': 'Synchronization',
    'label_content_filters': 'Content Filters',
    'label_minimum_rating': 'Minimum Rating',
    'label_minimum_rating_help': 'Minimum Kinopoisk rating for movies',
    'label_maximum_rating': 'Maximum Rating',
    'label_maximum_rating_help': 'Maximum Kinopoisk rating for movies',
    'label_minimum_votes': 'Minimum Votes',
    'label_minimum_votes_help': 'Minimum number of votes (popularity filter)',
    'label_year_range': 'Year Range',
    'label_start_year': 'Start Year',
    'label_start_year_help': 'Starting year for movie search',
    'label_end_year': 'End Year',
    'label_end_year_help': 'Ending year for movie search',
    'label_advanced_settings': 'Advanced Settings',
    'label_max_requests_per_run': 'Max Requests per Run',
    'label_max_requests_per_run_help': 'Maximum API requests per synchronization run (default: 250 for free tier, up to 1000 for premium)',
    'label_daily_request_limit': 'Daily Request Limit',
    'label_daily_request_limit_help': 'Total API requests allowed per day (default: 200 for free tier, higher for premium keys)',
    'label_auto_sync': 'Auto Sync',
    'label_auto_sync_help': 'Automatically synchronize on adapter start',
    'label_sync_interval': 'Sync Interval',
    'label_sync_interval_help': 'Interval between automatic synchronizations (if Auto Sync is enabled)',
    'label_status': 'Status',
    'label_web_server_status': 'Web Server Status',
    'label_server_url': 'Server URL: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Check \'server.url\' state for actual URL)',
    'label_synchronization_status': 'Synchronization Status',
    'label_total_movies': 'Total movies in database: Check \'sync.totalMovies\' state',
    'label_sync_info': 'Use the \'sync.start\' state to trigger synchronization. After sync completes, refresh the app (F5) to see new movies.',
    'label_help': 'Help',
    'label_help_text': 'For more information, visit the <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>GitHub repository</a>.'
  },
  'de': {
    'label_general_settings': 'Allgemeine Einstellungen',
    'label_web_server': 'Webserver',
    'label_port': 'Port',
    'label_port_help': 'Port für den Webserver (PWA-Anwendung)',
    'label_api_configuration': 'API-Konfiguration',
    'label_api_keys': 'API-Schlüssel',
    'label_api_keys_help': 'Kinopoisk-API-Schlüssel (ein oder mehrere). Der Adapter verwendet sie der Reihe nach. Drücken Sie \'+\', um einen neuen Schlüssel hinzuzufügen.',
    'label_api_key': 'API-Schlüssel',
    'label_get_api_key': 'Holen Sie sich Ihren API-Schlüssel unter: https://api.kinopoisk.dev/',
    'label_synchronization': 'Synchronisierung',
    'label_content_filters': 'Inhaltsfilter',
    'label_minimum_rating': 'Mindestbewertung',
    'label_minimum_rating_help': 'Mindestbewertung von Kinopoisk für Filme',
    'label_maximum_rating': 'Maximale Bewertung',
    'label_maximum_rating_help': 'Maximale Kinopoisk-Bewertung für Filme',
    'label_minimum_votes': 'Mindestanzahl der Stimmen',
    'label_minimum_votes_help': 'Mindestanzahl der Stimmen (Popularitätsfilter)',
    'label_year_range': 'Jahresbereich',
    'label_start_year': 'Startjahr',
    'label_start_year_help': 'Startjahr für die Filmsuche',
    'label_end_year': 'Endjahr',
    'label_end_year_help': 'Endjahr für die Filmsuche',
    'label_advanced_settings': 'Erweiterte Einstellungen',
    'label_max_requests_per_run': 'Max. Anfragen pro Durchlauf',
    'label_max_requests_per_run_help': 'Maximale API-Anfragen pro Synchronisierungsdurchlauf (Standard: 250 für kostenlosen Plan, bis zu 1000 für Premium)',
    'label_daily_request_limit': 'Tägliches Anfragelimit',
    'label_daily_request_limit_help': 'Gesamte API-Anfragen pro Tag (Standard: 200 für kostenlosen Plan, höher für Premium-Schlüssel)',
    'label_auto_sync': 'Automatische Synchronisierung',
    'label_auto_sync_help': 'Automatisch synchronisieren beim Adapter-Start',
    'label_sync_interval': 'Synchronisierungsintervall',
    'label_sync_interval_help': 'Intervall zwischen automatischen Synchronisierungen (wenn automatische Synchronisierung aktiviert ist)',
    'label_status': 'Status',
    'label_web_server_status': 'Webserver-Status',
    'label_server_url': 'Server-URL: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Überprüfen Sie den Status \'server.url\' für die tatsächliche URL)',
    'label_synchronization_status': 'Synchronisierungsstatus',
    'label_total_movies': 'Gesamtzahl der Filme in der Datenbank: Überprüfen Sie den Status \'sync.totalMovies\'',
    'label_sync_info': 'Verwenden Sie den Status \'sync.start\', um die Synchronisierung auszulösen. Nach Abschluss der Synchronisierung aktualisieren Sie die App (F5), um neue Filme anzuzeigen.',
    'label_help': 'Hilfe',
    'label_help_text': 'Weitere Informationen finden Sie im <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>GitHub-Repository</a>.'
  },
  'ru': {
    'label_general_settings': 'Основные настройки',
    'label_web_server': 'Веб-сервер',
    'label_port': 'Порт',
    'label_port_help': 'Порт для веб-сервера (PWA приложение)',
    'label_api_configuration': 'Конфигурация API',
    'label_api_keys': 'API ключи',
    'label_api_keys_help': 'API ключи Kinopoisk (один или несколько). Адаптер будет использовать их по очереди. Нажмите \'+\' для добавления нового ключа.',
    'label_api_key': 'API ключ',
    'label_get_api_key': 'Получите ваш API ключ на: https://api.kinopoisk.dev/',
    'label_synchronization': 'Синхронизация',
    'label_content_filters': 'Фильтры контента',
    'label_minimum_rating': 'Минимальный рейтинг',
    'label_minimum_rating_help': 'Минимальный рейтинг Kinopoisk для фильмов',
    'label_maximum_rating': 'Максимальный рейтинг',
    'label_maximum_rating_help': 'Максимальный рейтинг Kinopoisk для фильмов',
    'label_minimum_votes': 'Минимум голосов',
    'label_minimum_votes_help': 'Минимальное количество голосов (фильтр популярности)',
    'label_year_range': 'Диапазон лет',
    'label_start_year': 'Начальный год',
    'label_start_year_help': 'Начальный год для поиска фильмов',
    'label_end_year': 'Конечный год',
    'label_end_year_help': 'Конечный год для поиска фильмов',
    'label_advanced_settings': 'Расширенные настройки',
    'label_max_requests_per_run': 'Макс. запросов за запуск',
    'label_max_requests_per_run_help': 'Максимум API запросов за один запуск синхронизации (по умолчанию: 250 для бесплатного тарифа, до 1000 для премиум)',
    'label_daily_request_limit': 'Дневной лимит запросов',
    'label_daily_request_limit_help': 'Всего API запросов в день (по умолчанию: 200 для бесплатного тарифа, выше для премиум ключей)',
    'label_auto_sync': 'Автосинхронизация',
    'label_auto_sync_help': 'Автоматически синхронизировать при запуске адаптера',
    'label_sync_interval': 'Интервал синхронизации',
    'label_sync_interval_help': 'Интервал между автоматическими синхронизациями (если включена автосинхронизация)',
    'label_status': 'Статус',
    'label_web_server_status': 'Статус веб-сервера',
    'label_server_url': 'URL сервера: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Проверьте состояние \'server.url\' для актуального URL)',
    'label_synchronization_status': 'Статус синхронизации',
    'label_total_movies': 'Всего фильмов в базе: Проверьте состояние \'sync.totalMovies\'',
    'label_sync_info': 'Используйте состояние \'sync.start\' для запуска синхронизации. После завершения синхронизации обновите приложение (F5) для просмотра новых фильмов.',
    'label_help': 'Справка',
    'label_help_text': 'Для получения дополнительной информации посетите <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>репозиторий GitHub</a>.'
  }
};
