/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'en': {
    'General Settings': 'General Settings',
    'Web Server': 'Web Server',
    'Port': 'Port',
    'Port for the web server (PWA application)': 'Port for the web server (PWA application)',
    'API Configuration': 'API Configuration',
    'API Keys': 'API Keys',
    'Kinopoisk API keys (one or more). The adapter will use them in rotation. Press \'+\' to add a new key.': 'Kinopoisk API keys (one or more). The adapter will use them in rotation. Press \'+\' to add a new key.',
    'API Key': 'API Key',
    'Get your API key at: https://api.kinopoisk.dev/': 'Get your API key at: https://api.kinopoisk.dev/',
    'Synchronization': 'Synchronization',
    'Content Filters': 'Content Filters',
    'Minimum Rating': 'Minimum Rating',
    'Minimum Kinopoisk rating for movies': 'Minimum Kinopoisk rating for movies',
    'Maximum Rating': 'Maximum Rating',
    'Maximum Kinopoisk rating for movies': 'Maximum Kinopoisk rating for movies',
    'Minimum Votes': 'Minimum Votes',
    'Minimum number of votes (popularity filter)': 'Minimum number of votes (popularity filter)',
    'Year Range': 'Year Range',
    'Start Year': 'Start Year',
    'Starting year for movie search': 'Starting year for movie search',
    'End Year': 'End Year',
    'Ending year for movie search': 'Ending year for movie search',
    'Advanced Settings': 'Advanced Settings',
    'Max Requests per Run': 'Max Requests per Run',
    'Maximum API requests per synchronization run (default: 250 for free tier, up to 1000 for premium)': 'Maximum API requests per synchronization run (default: 250 for free tier, up to 1000 for premium)',
    'Daily Request Limit': 'Daily Request Limit',
    'Total API requests allowed per day (default: 200 for free tier, higher for premium keys)': 'Total API requests allowed per day (default: 200 for free tier, higher for premium keys)',
    'Auto Sync': 'Auto Sync',
    'Automatically synchronize on adapter start': 'Automatically synchronize on adapter start',
    'Sync Interval': 'Sync Interval',
    'Interval between automatic synchronizations (if Auto Sync is enabled)': 'Interval between automatic synchronizations (if Auto Sync is enabled)',
    'Status': 'Status',
    'Web Server Status': 'Web Server Status',
    'Server URL: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Check \'server.url\' state for actual URL)': 'Server URL: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Check \'server.url\' state for actual URL)',
    'Synchronization Status': 'Synchronization Status',
    'Total movies in database: Check \'sync.totalMovies\' state': 'Total movies in database: Check \'sync.totalMovies\' state',
    'Use the \'sync.start\' state to trigger synchronization. After sync completes, refresh the app (F5) to see new movies.': 'Use the \'sync.start\' state to trigger synchronization. After sync completes, refresh the app (F5) to see new movies.',
    'Help': 'Help',
    'For more information, visit the <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>GitHub repository</a>.': 'For more information, visit the <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>GitHub repository</a>.'
  },
  'de': {
    'General Settings': 'Allgemeine Einstellungen',
    'Web Server': 'Webserver',
    'Port': 'Port',
    'Port for the web server (PWA application)': 'Port für den Webserver (PWA-Anwendung)',
    'API Configuration': 'API-Konfiguration',
    'API Keys': 'API-Schlüssel',
    'Kinopoisk API keys (one or more). The adapter will use them in rotation. Press \'+\' to add a new key.': 'Kinopoisk-API-Schlüssel (ein oder mehrere). Der Adapter verwendet sie der Reihe nach. Drücken Sie \'+\', um einen neuen Schlüssel hinzuzufügen.',
    'API Key': 'API-Schlüssel',
    'Get your API key at: https://api.kinopoisk.dev/': 'Holen Sie sich Ihren API-Schlüssel unter: https://api.kinopoisk.dev/',
    'Synchronization': 'Synchronisierung',
    'Content Filters': 'Inhaltsfilter',
    'Minimum Rating': 'Mindestbewertung',
    'Minimum Kinopoisk rating for movies': 'Mindestbewertung von Kinopoisk für Filme',
    'Maximum Rating': 'Maximale Bewertung',
    'Maximum Kinopoisk rating for movies': 'Maximale Kinopoisk-Bewertung für Filme',
    'Minimum Votes': 'Mindestanzahl der Stimmen',
    'Minimum number of votes (popularity filter)': 'Mindestanzahl der Stimmen (Popularitätsfilter)',
    'Year Range': 'Jahresbereich',
    'Start Year': 'Startjahr',
    'Starting year for movie search': 'Startjahr für die Filmsuche',
    'End Year': 'Endjahr',
    'Ending year for movie search': 'Endjahr für die Filmsuche',
    'Advanced Settings': 'Erweiterte Einstellungen',
    'Max Requests per Run': 'Max. Anfragen pro Durchlauf',
    'Maximum API requests per synchronization run (default: 250 for free tier, up to 1000 for premium)': 'Maximale API-Anfragen pro Synchronisierungsdurchlauf (Standard: 250 für kostenlosen Plan, bis zu 1000 für Premium)',
    'Daily Request Limit': 'Tägliches Anfragelimit',
    'Total API requests allowed per day (default: 200 for free tier, higher for premium keys)': 'Gesamte API-Anfragen pro Tag (Standard: 200 für kostenlosen Plan, höher für Premium-Schlüssel)',
    'Auto Sync': 'Automatische Synchronisierung',
    'Automatically synchronize on adapter start': 'Automatisch synchronisieren beim Adapter-Start',
    'Sync Interval': 'Synchronisierungsintervall',
    'Interval between automatic synchronizations (if Auto Sync is enabled)': 'Intervall zwischen automatischen Synchronisierungen (wenn automatische Synchronisierung aktiviert ist)',
    'Status': 'Status',
    'Web Server Status': 'Webserver-Status',
    'Server URL: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Check \'server.url\' state for actual URL)': 'Server-URL: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Überprüfen Sie den Status \'server.url\' für die tatsächliche URL)',
    'Synchronization Status': 'Synchronisierungsstatus',
    'Total movies in database: Check \'sync.totalMovies\' state': 'Gesamtzahl der Filme in der Datenbank: Überprüfen Sie den Status \'sync.totalMovies\'',
    'Use the \'sync.start\' state to trigger synchronization. After sync completes, refresh the app (F5) to see new movies.': 'Verwenden Sie den Status \'sync.start\', um die Synchronisierung auszulösen. Nach Abschluss der Synchronisierung aktualisieren Sie die App (F5), um neue Filme anzuzeigen.',
    'Help': 'Hilfe',
    'For more information, visit the <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>GitHub repository</a>.': 'Weitere Informationen finden Sie im <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>GitHub-Repository</a>.'
  },
  'ru': {
    'General Settings': 'Основные настройки',
    'Web Server': 'Веб-сервер',
    'Port': 'Порт',
    'Port for the web server (PWA application)': 'Порт для веб-сервера (PWA приложение)',
    'API Configuration': 'Конфигурация API',
    'API Keys': 'API ключи',
    'Kinopoisk API keys (one or more). The adapter will use them in rotation. Press \'+\' to add a new key.': 'API ключи Kinopoisk (один или несколько). Адаптер будет использовать их по очереди. Нажмите \'+\' для добавления нового ключа.',
    'API Key': 'API ключ',
    'Get your API key at: https://api.kinopoisk.dev/': 'Получите ваш API ключ на: https://api.kinopoisk.dev/',
    'Synchronization': 'Синхронизация',
    'Content Filters': 'Фильтры контента',
    'Minimum Rating': 'Минимальный рейтинг',
    'Minimum Kinopoisk rating for movies': 'Минимальный рейтинг Kinopoisk для фильмов',
    'Maximum Rating': 'Максимальный рейтинг',
    'Maximum Kinopoisk rating for movies': 'Максимальный рейтинг Kinopoisk для фильмов',
    'Minimum Votes': 'Минимум голосов',
    'Minimum number of votes (popularity filter)': 'Минимальное количество голосов (фильтр популярности)',
    'Year Range': 'Диапазон лет',
    'Start Year': 'Начальный год',
    'Starting year for movie search': 'Начальный год для поиска фильмов',
    'End Year': 'Конечный год',
    'Ending year for movie search': 'Конечный год для поиска фильмов',
    'Advanced Settings': 'Расширенные настройки',
    'Max Requests per Run': 'Макс. запросов за запуск',
    'Maximum API requests per synchronization run (default: 250 for free tier, up to 1000 for premium)': 'Максимум API запросов за один запуск синхронизации (по умолчанию: 250 для бесплатного тарифа, до 1000 для премиум)',
    'Daily Request Limit': 'Дневной лимит запросов',
    'Total API requests allowed per day (default: 200 for free tier, higher for premium keys)': 'Всего API запросов в день (по умолчанию: 200 для бесплатного тарифа, выше для премиум ключей)',
    'Auto Sync': 'Автосинхронизация',
    'Automatically synchronize on adapter start': 'Автоматически синхронизировать при запуске адаптера',
    'Sync Interval': 'Интервал синхронизации',
    'Interval between automatic synchronizations (if Auto Sync is enabled)': 'Интервал между автоматическими синхронизациями (если включена автосинхронизация)',
    'Status': 'Статус',
    'Web Server Status': 'Статус веб-сервера',
    'Server URL: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Check \'server.url\' state for actual URL)': 'URL сервера: <a href=\'http://localhost:3000\' target=\'_blank\'>http://localhost:3000</a> (Проверьте состояние \'server.url\' для актуального URL)',
    'Synchronization Status': 'Статус синхронизации',
    'Total movies in database: Check \'sync.totalMovies\' state': 'Всего фильмов в базе: Проверьте состояние \'sync.totalMovies\'',
    'Use the \'sync.start\' state to trigger synchronization. After sync completes, refresh the app (F5) to see new movies.': 'Используйте состояние \'sync.start\' для запуска синхронизации. После завершения синхронизации обновите приложение (F5) для просмотра новых фильмов.',
    'Help': 'Справка',
    'For more information, visit the <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>GitHub repository</a>.': 'Для получения дополнительной информации посетите <a href=\'https://github.com/sadam6752-tech/ioBroker.movieswipe\' target=\'_blank\'>репозиторий GitHub</a>.'
  }
};
